substitutions:
  device_name: "PC LED"
  name: "pc-led"

esphome:
  name: "${name}"
  comment: "${device_name}"
  friendly_name: "${device_name}"
  name_add_mac_suffix: true
  project:
    name: "l7ssha.led"
    version: "1.1"

dashboard_import:
  package_import_url: github://l7ssha/esphome/pc-led.yaml@main
  import_full_config: false

esp32:
  board: upesy_wroom
  framework:
    type: arduino

logger:

api:

ota:

wifi:
  power_save_mode: none
  ap:
    ssid: "${name} Hotspot"
    password: "${name}-123"

captive_portal:

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2811
    pin: 5
    num_leds: 60
    name: "NeoPixel Light"
    effects:
      - random:
      - pulse:
      - strobe:
      - flicker:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: uptime
    name: Uptime
    entity_category: "diagnostic"

button:
  - platform: factory_reset
    name: "Restart with Factory Default Settings"
    entity_category: "config" 

  - platform: restart
    name: "Restart"
    entity_category: "config"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "Connected SSID"
    mac_address:
      name: "Mac Address"